---
- name: iredmail
  hosts: iredmail
  become: yes
  become_method: sudo
  remote_user: '{{admin_username}}'
  gather_facts: False
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get -y install python'


- name: iredmail
  hosts: iredmail
  become: yes
  become_method: sudo
  remote_user: '{{admin_username}}'
  tasks:

  - import_tasks: common.yml

  - name: download iredmail package
    unarchive:
      src: https://bitbucket.org/zhb/iredmail/downloads/iRedMail-0.9.9.tar.bz2
      dest: /
      remote_src: yes
      



